# Change baseurl before deploy
baseurl = "https://miguelog.com"
languageCode = "en-us"
title = "Miguel Ocampo-Gooding"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
pagerSize = 5