# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Miguel
tagline:          'Miguel Ocampo-Gooding'
description:      'Front End Developer'
url:              http://miguelis.me
baseurl:          miguelis.me/

author:
  name:           'Miguel Ocampo-Gooding'
  url:            https://twitter.com/migue_og
  resume:         MiguelCV.pdf

paginate:         5


github:
  repo:          https://github.com/migueog

codepen:
  site:          http://codepen.io/miguelog/

collections:
- projects
- posts
