# Dependencies
gems:             [jekyll-paginate]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Miguel
tagline:          'Miguel Ocampo-Gooding'
description:      'Miguel's Blog
url:              miguelis.me
baseurl:          /

author:
  name:           'Miguel Ocampo-Gooding'
  url:            https://twitter.com/migue_og
  resume:         MiguelCV.pdf

paginate:         5


github:
  repo:          https://github.com/migueog


