# Dependencies
gems:             [jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Miguel
tagline:          'Miguel Ocampo-Gooding'
description:      'Writings from Miguel'
url:              miguelis.me
baseurl:          /

author:
  name:           'Miguel Ocampo-Gooding'
  url:            https://twitter.com/migue_og

paginate:         5


github:
  repo:          https://github.com/migueog
